version: "3.3"
services:
    www:
        container_name: "client"
        build:
            context: .
            dockerfile: php.dockerfile
        ports:
            - "10:10"
        volumes:
            - ./public_html:/var/www/html
networks:
  myapp:
    driver: bridge